Add right-click options to Schema Browser items
halcyon-tech/vscode-db2i pull request #18
Opened 2023-06-23 18:11 UTC by shamby87

2023-06-26 16:08 UTC, worksofliam requested changes
@shamby87 A good change, but I think the code could be a little cleaner.

I am not a big fan of embedding queries into commands. If we can turn them into their own methods we can re-use them. The `database` directory has some database queries wrapped into methods and I'd like to see more added instead of via this PR.

Also, uou are you using two ways to run a query, but I think it's worth standardising on one (I prefer the `runSQL` over the command)

* https://github.com/halcyon-tech/vscode-db2i/pull/18/files#diff-87342e72eeaa1ab60a5dad8db3c4d2464e1fa66043961d135588854c0e168ab2R169
* https://github.com/halcyon-tech/vscode-db2i/pull/18/files#diff-87342e72eeaa1ab60a5dad8db3c4d2464e1fa66043961d135588854c0e168ab2R149

Feel free to reach out to me and we can work on this together some.

2023-06-26 16:08 UTC, worksofliam commented on src/views/schemaBrowser.ts
> +            const content = `SELECT SQL_OBJECT_TYPE, SCHEMA_NAME, SQL_NAME, LIBRARY_NAME,
This query belongs in an API instead of embedding the query in the command.

2023-06-26 16:08 UTC, worksofliam commented on src/views/schemaBrowser.ts
> +            const content = `SELECT * FROM QSYS2.SYSINDEXSTAT WHERE TABLE_SCHEMA = '${object.schema}' and TABLE_NAME = '${object.name}'`;
This query belongs in an API instead of embedding the query in the command.

2023-06-26 16:08 UTC, worksofliam commented on src/views/schemaBrowser.ts
> +            const content = `SELECT * FROM QSYS2.SYSIXADV WHERE TABLE_SCHEMA = '${object.schema}' and TABLE_NAME = '${object.name}'`;
This query belongs in an API instead of embedding the query in the command.

2023-06-26 16:08 UTC, worksofliam commented on src/views/schemaBrowser.ts
> +              const query = `DELETE FROM QSYS2.SYSIXADV WHERE TABLE_SCHEMA = '${object.schema}' and TABLE_NAME = '${object.name}'`;
This query belongs in an API instead of embedding the query in the command.

2023-06-27 16:14 UTC, worksofliam requested changes
Change to using APIs is almost perfect. Last part that needs some cleaning up is removing any 'ui' code (`showXMessage`) from the API methods and instead letting the commands/UI code handle them.

2023-06-27 16:41 UTC, worksofliam approved these changes
Code looks good to me. @davecharron over to you for some testing.

2023-06-27 17:09 UTC, davecharron commented
### Rename action - Bug

Cancelling the rename prompt actually performs the rename action using the name 'undefinded'

2023-06-27 17:15 UTC, davecharron commented
### Clear action - Comments

1. There is no confirmation message after clicking Yes to clear the data.
2. Do we really need No/Yes/Cancel on the confirmation?  No and Cancel would seem to do exactly the same thing.

2023-06-27 18:10 UTC, davecharron commented
# Testing Feedback...  In progress, actively updating this comment

## General
ℹ️ Do we really need No/Yes/Cancel on the confirmation dialogs?  No and Cancel would seem to do exactly the same thing. 

## Clear action
⚠️ There is no confirmation message after clicking Yes to clear the data.
⚠️ The failure message when the object does not exist or the clear fails because the object is locked or user doesn't have authority to it, takes a long time ( 30 seconds? ) to display, if it does at all.  
If the API we use to send the command to the system allows job level control it would be good to change the default wait time to something really small like 1 rather than the default 30 so the feedback is more timely.

## Copy data
ℹ️ I would suggest that Data be capitalized.  This comment really applies to all extension development in that the capitalization of menu items should be consistent.
⚠️ The custom UI does not allow for specifying a member name and label.
⚠️ There is no confirmation message after clicking Copy to copy the data.

## Delete
⚠️ Same comment as that for the Clear action with regard to failure messages.

## Rename action
🛑 Cancelling the rename prompt actually performs the rename action using the name 'undefinded'
⚠️ The action should really be issuing an [SQL RENAME](https://www.ibm.com/docs/en/i/7.5?topic=statements-rename) rather than the RNMOBJ CL command.  This would also allow for setting both the SQL and system identifier for the object.

2023-06-27 18:53 UTC, shamby87 commented
> Do we really need No/Yes/Cancel on the confirmation dialogs? No and Cancel would seem to do exactly the same thing.

- This is a good question and it is something I didn't like. For the popup message, it requires that there be a default "nothing" action for if a user exits the window, which is the `cancel` button. I can set the `no` button to replace the `cancel` so there would just be 2 buttons, but then I have no way to make `no` the default answer like we discussed. Having it this way allows `no` to be the default. @worksofliam do you have any way around this? [Here](https://github.com/halcyon-tech/vscode-db2i/pull/18/files#diff-87342e72eeaa1ab60a5dad8db3c4d2464e1fa66043961d135588854c0e168ab2R160-R162) is an example of where I do this.


> There is no confirmation message after clicking Yes to clear the data.
> There is no confirmation message after clicking Copy to copy the data.

- Confirmation as in "Success the data was cleared" or another "Yes I really want to do this"?


> The failure message when the object does not exist or the clear fails because the object is locked or user doesn't have authority to it, takes a long time ( 30 seconds? ) to display, if it does at all.
If the API we use to send the command to the system allows job level control it would be good to change the default wait time to something really small like 1 rather than the default 30 so the feedback is more timely.

- @worksofliam I used `getInstance().getConnection().runCommand()`, is there a way to control the wait time for a response here? Is there an environment variable that can control this?


I'll also look into fixing the other issues, thank you for all the feedback!

2023-06-27 19:09 UTC, worksofliam commented
@shamby87 There is no wait time support, but you should look into the `withProgress` VS Code API to help show the user something is running in the background.

2023-06-27 21:57 UTC, davecharron requested changes
I've looked through the code and have added some comments.

2023-06-27 21:57 UTC, davecharron commented on package.json
> +          "when": "viewItem == table || viewItem == view || viewItem == alias || viewItem == constraint || viewItem == function || viewItem == variable || viewItem == index || viewItem == procedure |
Missing support for deleting triggers

2023-06-27 21:57 UTC, davecharron commented on src/database/schemas.ts
> +  static async deleteObject(objectPath: string, type: string): Promise<void> {
Instead of objectPath, do we want to maintain the pattern of specifying schema and object name as separate values?

2023-06-27 21:57 UTC, davecharron commented on src/database/schemas.ts
> +    const command = `RNMOBJ OBJ(${schema}/${oldName}) OBJTYPE(*FILE) NEWOBJ(${newName})`;
Use the RENAME SQL statement instead of RNMOBJ

2023-06-27 21:57 UTC, davecharron commented on src/database/table.ts
> +              FROM TABLE(SYSTOOLS.RELATED_OBJECTS('${schema}', '${name}')) ORDER BY SQL_NAME`;
I would suggest the following column order:
```
SQL_NAME, SYSTEM_NAME, SCHEMA_NAME, LIBRARY_NAME, SQL_OBJECT_TYPE, 
              OBJECT_OWNER, LAST_ALTERED, OBJECT_TEXT, LONG_COMMENT
```
Would also order by SQL_OBJECT_TYPE then by SQL_NAME

2023-06-27 21:57 UTC, davecharron commented on src/database/table.ts
> +    const content = `SELECT * FROM QSYS2.SYSIXADV WHERE TABLE_SCHEMA = '${schema}' and TABLE_NAME = '${name}'`;
Should order the results by TIMES_ADVISED descending.

2023-06-27 21:57 UTC, davecharron commented on src/views/schemaBrowser.ts
> +              Table.clearFile(object.schema, object.name);
I think this might need to use `await`

2023-06-27 21:57 UTC, davecharron commented on src/views/schemaBrowser.ts
> +          if(page && page.data) {
> SonarLint suggests: Prefer using an optional chain expression instead, as it's more concise and easier to read.sonarlint(typescript:S6582)
`page?.data`

2023-06-27 21:57 UTC, davecharron commented on src/views/schemaBrowser.ts
> +              Table.clearAdvisedIndexes(object.schema, object.name);
I think this might need to use await

2023-06-29 17:08 UTC, davecharron approved these changes
I have no further comments.  Code looks good.

2023-06-29 20:06 UTC, davecharron commented
> > Do we really need No/Yes/Cancel on the confirmation dialogs? No and Cancel would seem to do exactly the same thing.
> 
>     * This is a good question and it is something I didn't like. For the popup message, it requires that there be a default "nothing" action for if a user exits the window, which is the `cancel` button. I can set the `no` button to replace the `cancel` so there would just be 2 buttons, but then I have no way to make `no` the default answer like we discussed. Having it this way allows `no` to be the default.

What do folks think about having just two buttons then?  One that affirms the action (Ex. Delete) along with the Cancel button.  The wording of the messages might necessarily need to change to make sense.

Example:


[Notifications | Visual Studio Code Extension API](https://code.visualstudio.com/api/ux-guidelines/notifications)

2023-06-29 20:07 UTC, davecharron commented
Sorry, didn't mean to close the PR.  Was adding a comment and meant to abandon it.

2023-06-29 20:15 UTC, davecharron reviewed
One more suggestion

2023-06-29 20:15 UTC, davecharron commented on src/views/schemaBrowser.ts
> +            prompt: "Enter new name",
Pre-populate the rename prompt with the current object name.
`value: object.name`

2023-06-29 20:27 UTC, davecharron commented on src/views/schemaBrowser.ts
> +            .loadPage<any>('Copy File');
Include the qualified object name in the page title.
```suggestion
            .loadPage<any>(`Copy File - ${object.schema}.${object.name}`);
```

2023-06-30 19:44 UTC, worksofliam approved these changes
Did a final review include a change to the API code with Brock. Let's merge this!

2023-06-30 19:44 UTC, merged