Wire paging queries into UI
halcyon-tech/vscode-db2i pull request #31
Opened 2023-07-10 20:09 UTC by ThePrez

2023-07-11 16:49 UTC, worksofliam requested changes
@ThePrez Check out my comment about query history, then I will follow up with some testing

2023-07-12 04:15 UTC, ThePrez commented on src/views/results/index.ts
> +              if (statement.type === `statement`) {
Why should some statements not make it to the query history?

2023-07-12 14:02 UTC, worksofliam commented on src/views/results/index.ts
> +              if (statement.type === `statement`) {
We use this query API for things like getting advised indexes and such from the Schema Browser.

2023-07-12 14:35 UTC, ThePrez commented on src/views/results/index.ts
> +              if (statement.type === `statement`) {
ahh, makes sense. Thank you

2023-07-12 17:07 UTC, ThePrez commented on src/views/results/index.ts
> +              if (statement.type === `statement`) {
put back, https://github.com/halcyon-tech/vscode-db2i/pull/31/commits/c565870213edd074c917c1b3b9c49bdfd257e504

2023-07-12 17:46 UTC, worksofliam requested changes
Code looks good, but let's do some cleanup too. In `views/results/html.ts`, we can now remove these two methods as they are no longer used anywhere.

* `generateResults`
* `generateTable`

2023-07-12 17:52 UTC, ThePrez commented
> Code looks good, but let's do some cleanup too. In `views/results/html.ts`, we can now remove these two methods as they are no longer used anywhere.
> 
>     * `generateResults`
> 
>     * `generateTable`

Good catch! https://github.com/halcyon-tech/vscode-db2i/pull/31/commits/0b245c7a10064a26fd5994ecfcd9ee7514239208

2023-07-12 19:18 UTC, worksofliam commented
Thank you @ThePrez - beautiful PR! More deletions than additions. I wish I could give you an award

2023-07-12 19:18 UTC, worksofliam commented
Testing complete. Great job

2023-07-12 19:18 UTC, merged